services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3005:3005'
    environment:
      PORT: 3005
      DATABASE_HOST: 'postgres_db'
      DATABASE_PORT: 5432
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'password'
      DATABASE_DB: 'postgres'
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
